---

variables:
    NODE_VERSION: 12.18.3-buster
    DOCKER_YAMLLINT_VERSION: 2.0.0

include:
-   project: f4/gitlab-ci-tools
    ref: master
    file: /templates/node-js.yml

code_style:
    script:
    - npm run test-code-style

test:
    script:
    - npm test
